# Generated by Django 4.2.6 on 2023-10-16 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acao',
            old_name='Lucro_prejuizo',
            new_name='lucro_prejuizo',
        ),
    ]
