# Generated by Django 4.2.6 on 2023-10-17 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_lucro_prejuizo_acao_lucro_prejuizo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acao',
            old_name='ticker',
            new_name='codigo',
        ),
    ]
